name: app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.7.3+36
environment:
  sdk: '>=3.10.0 <4.0.0'  # â† UPDATE THIS LINE
  flutter: ">=3.24.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^19.0.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.10
  transparent_image: ^2.0.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.2.0+3
  intl: ^0.20.2
  record: ^5.2.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  dio: ^5.0.0
  socket_io_client: ^2.0.3+1
  country_code_picker: ^3.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.1.0
  permission_handler: ^11.0.1
  web_socket_channel: ^2.4.0
  provider: ^6.1.5
  url_launcher: ^6.2.1
  mime: ^1.0.4
  emoji_picker_flutter: ^1.6.4
  logger: ^2.0.2
  cached_network_image: ^3.3.1
  go_router: ^14.0.0
  share_plus: ^10.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  flutter_app_badger: ^1.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  record_platform_interface: 1.2.0


flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/logo/logo.png"
    adaptive_icon_background: "#FFFFFF"
    adaptive_icon_foreground: "assets/logo/logo.png"
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo/logo.png
    - assets/logo/logo_no_background.png
    - assets/logo/logo_with_background.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
